version: 2.1

jobs:
  test:
    docker:
      - image:circleci/node:14 

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run NightwatchJS tests
          command: npm test

      - store_artifacts:
          path: reports
          destination: reports

      - store_test_results:
          path: reports

workflows:
  version: 2
  test:
    jobs:
      - test
