version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:19.4

    steps:
      - setup_remote_docker:
          version: 20.10.8
      - run:
          name: Pull Docker image
          command: docker pull circleci/node:19.4
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run UI Tests
          command: npm run test:ui
          
      - store_artifacts:
          path: reports
          destination: reports

      - store_test_results:
          path: reports

workflows:
  version: 2
  test:
    jobs:
      - test
