version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:latest

    working_directory: ui-tests/tests

    steps:
      - setup_remote_docker
      - checkout
      
      - run:
          name: Adjust Permissions
          command: |
            sudo chmod +w https://github.com/baseltarek95/
            sudo mkdir git@github.com:baseltarek95/SDET.git

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run UI Tests
          command: npm run test:ui

      - store_artifacts:
          path: reports
          destination: reports

      - store_test_results:
          path: reports

workflows:
  version: 2
  test:
    jobs:
      - test
