version: 2.1

jobs:
  test:
    docker:
      - image:circleci/node:14 

    steps:
      - checkout

      - run:
          name: Run UI Tests
          command: npm run test:ui
          
      - store_artifacts:
          path: reports
          destination: reports

      - store_test_results:
          path: reports

workflows:
  version: 2
  test:
    jobs:
      - test
