version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:latest
    working_directory: ui-tests/tests

    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Configure SSH Keys
          command: |
            set -e

            # Workaround old docker images with incorrect $HOME
            if [ "${HOME}" = "/" ]; then
              export HOME=$(getent passwd $(id -un) | cut -d: -f6)
            fi

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run UI Tests
          command: npm run test:ui

      - store_artifacts:
          path: reports
          destination: reports

      - store_test_results:
          path: reports

workflows:
  version: 2
  test:
    jobs:
      - test
